version: '3'

services:
    redis:
        image: redis
        ports:
            - 6379:6379
        sysctls:
            net.core.somaxconn: '511'
    db:
        image: mongo
        ports:
            - 27017:27017
    web:
        build: .
        ports:
            - 7000:7000
        command: npm start
        depends_on:
            - db
